#!/usr/bin/env python3
"""Render ReqogniLoom client documentation from ``clients/registry.yaml``.

Single Source of Truth (#1171, Bundle B0): the German/English client pages and
the cross-client matrix are *generated*, never hand-maintained. A hand edit of a
generated file is a deliberate CI failure (``--check``), which is what keeps the
OpenCode-style contradiction from reappearing.

Usage::

    python scripts/clients/render.py            # write artifacts
    python scripts/clients/render.py --check    # fail if artifacts are stale

The renderer is idempotent: a second run changes nothing. It also validates the
shipped snippets referenced by the registry (transport path + env-var
convention) so a drift between registry and ``dist/**`` is caught here.

Only stdlib + PyYAML are used; run it in the backend/CI environment.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
REGISTRY_PATH = REPO_ROOT / "clients" / "registry.yaml"
DOCS_DIR = REPO_ROOT / "docs" / "clients"

GENERATED_HEADER = (
    "<!-- generated by scripts/clients/render.py from clients/registry.yaml "
    "— do not edit by hand -->"
)

#: Client ids whose doc file is generated; also the doc slug.
CLIENT_IDS = (
    "claude-code",
    "codex",
    "opencode",
    "kimi-code",
    "antigravity",
    "hermes",
)

_TRANSPORT_LABEL = {
    "streamable_http": "Streamable HTTP",
    "sse": "SSE",
    "stdio": "stdio bridge",
}


def load_registry(path: Path = REGISTRY_PATH) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle)
    if not isinstance(data, dict) or "clients" not in data:
        raise SystemExit(f"{path}: not a valid client registry")
    return data


def _code_blocks(blocks: Iterable[dict[str, str]] | None) -> str:
    out: list[str] = []
    for block in blocks or []:
        text = block["text"].rstrip("\n")
        out.append(f"```{block['lang']}\n{text}\n```")
    return "\n\n".join(out)


def _bullets(items: Iterable[str] | None) -> str:
    return "\n".join(f"- {item}" for item in (items or []))


def render_client(client: dict[str, Any], *, lang: str) -> str:
    de = lang == "de"
    url_path = client.get("url_path") or ""
    title = (
        f"# {client['name']} — ReqogniLoom-Anbindung"
        if de
        else f"# {client['name']} — ReqogniLoom integration"
    )
    stand = "Stand" if de else "as of"
    transport = _TRANSPORT_LABEL.get(client["transport"], client["transport"])

    overview_rows = [
        ("Transport", transport),
        ("Endpoint", f"`{url_path}`" if url_path else "stdio bridge"),
        ("Auth", f"`{client['auth_header']}`"),
        ("Zielstufe" if de else "Target level", client["target_level"]),
        ("Getestet" if de else "Tested", client["tested_version"]),
    ]
    overview = "\n".join(f"| {k} | {v} |" for k, v in overview_rows)

    parts: list[str] = [
        GENERATED_HEADER,
        "",
        title,
        f"> {stand}: {client['tested_version']} · `{client['id']}`",
        "",
        "| | |",
        "|---|---|",
        overview,
        "",
    ]

    parts += [
        "## 1. " + ("Voraussetzungen" if de else "Prerequisites"),
        "",
        _bullets(client["prereq_de" if de else "prereq_en"]),
        "",
    ]

    parts += [
        "## 2. " + ("Installation (ein Befehl)" if de else "Installation (one command)"),
        "",
        _code_blocks(client["install_de" if de else "install_en"]),
        "",
    ]

    parts += [
        "## 3. " + ("Konfiguration" if de else "Configuration"),
        "",
        (
            "Vollständige, generierte Konfiguration (Env-Var-Referenzen, nie ein "
            "literaler Key):"
            if de
            else "Complete, generated configuration (env-var references, never a literal key):"
        ),
        "",
        _code_blocks(client["fallback_de" if de else "fallback_en"]),
        "",
    ]

    provider = client.get("provider_de" if de else "provider_en") or []
    if provider:
        parts += [
            "## 4. " + ("Modell / Provider" if de else "Model / Provider"),
            "",
            _bullets(provider),
            "",
        ]

    verify = client["verify"]
    parts += [
        "## 5. " + ("Verifikation" if de else "Verification"),
        "",
        f"- **{'Befehl' if de else 'Command'}:** `{verify['command']}`",
        f"- **{'Erwartet' if de else 'Expected'}:** "
        + verify["expected_de" if de else "expected_en"],
        f"- **{'Tool-Call-Ergebnis' if de else 'Tool-call result'}:** {verify['tool_result']}",
        "",
    ]

    parts += [
        "## 6. " + ("Fallstricke" if de else "Pitfalls"),
        "",
        _bullets(client["pitfalls_de" if de else "pitfalls_en"]),
        "",
    ]

    parts += [
        "## 7. " + ("Rechte & Key-Scope" if de else "Roles & key scope"),
        "",
        _bullets(client["roles_de" if de else "roles_en"]),
        "",
    ]

    parts += [
        "## 8. " + ("Update / Deinstallation" if de else "Update / uninstall"),
        "",
        _bullets(client["update_de" if de else "update_en"]),
        "",
    ]
    return "\n".join(parts).rstrip("\n") + "\n"


def render_matrix(registry: dict[str, Any], *, lang: str) -> str:
    de = lang == "de"
    clients = registry["clients"]
    conv = registry["conventions"]
    smoke = registry["smoke"]
    title = (
        "# ReqogniLoom — MCP-Client-Anbindung"
        if de
        else "# ReqogniLoom — MCP client integration"
    )
    parts: list[str] = [
        GENERATED_HEADER,
        "",
        title,
        "",
        (
            "Ein Client, eine Seite, **Deutsch und Englisch**. Alle Seiten sind "
            "aus `clients/registry.yaml` generiert; manuelle Änderungen sind ein "
            "CI-Fehler."
            if de
            else "One client, one page, **German and English**. Every page is "
            "generated from `clients/registry.yaml`; manual edits are a CI failure."
        ),
        "",
        "## Matrix",
        "",
        "| Client | Transport | Auth | "
        + ("Zielstufe" if de else "Target") + " | "
        + ("Seite" if de else "Page") + " |",
        "|---|---|---|---|---|",
    ]
    for client in clients:
        link = f"[{client['name']}]({client['id']}.md)"
        parts.append(
            f"| {client['name']} | "
            f"{_TRANSPORT_LABEL.get(client['transport'], client['transport'])} | "
            f"`{client['auth_header']}` | {client['target_level']} | {link} |"
        )
    parts.append("")

    parts += [
        "## " + ("Konventionen" if de else "Conventions"),
        "",
        f"- MCP-URL: `${{{conv['mcp_url_env']}}}`",
        f"- API-Key: `${{{conv['api_key_env']}}}` (Präfix `{conv['api_key_prefix']}`)"
        if de
        else f"- API key: `${{{conv['api_key_env']}}}` (prefix `{conv['api_key_prefix']}`)",
        f"- Auth-Header (Standard): `{conv['default_auth_header']}` — "
        + ("**Ausnahme Codex: Bearer**." if de else "**exception Codex: Bearer**."),
        "",
        "### " + ("Transport-Entscheidung" if de else "Transport decision"),
        "",
        _bullets(conv["transport_rule_de" if de else "transport_rule_en"]),
        "",
        "## " + ("Einheitlicher Smoke-Test" if de else "Unified smoke test"),
        "",
        f"- **{'Aufgabe' if de else 'Task'}:** {smoke['task_de' if de else 'task_en']}",
        f"- **{'Zweitabfrage' if de else 'Second query'}:** "
        + smoke["second_de" if de else "second_en"],
        f"- **{'Bestanden' if de else 'Pass'}:** {smoke['pass_de' if de else 'pass_en']}",
        "",
    ]
    return "\n".join(parts).rstrip("\n") + "\n"


def _expect(condition: bool, message: str, problems: list[str]) -> None:
    if not condition:
        problems.append(message)


def validate_artifacts(registry: dict[str, Any]) -> list[str]:
    """Lightweight registry <-> shipped-artifact guard.

    Proves that every referenced config artifact exists, carries the registry's
    transport path, and never embeds a literal ``reqlo_`` key. The deep parity
    checks live in ``dist/test_mcp_convention_parity.py``; this is the link from
    the single source of truth to those artifacts.
    """
    problems: list[str] = []
    conv = registry["conventions"]
    for client in registry["clients"]:
        artifact = client.get("config_artifact") or ""
        if not artifact:
            continue
        path = REPO_ROOT / artifact
        _expect(path.is_file(), f"{client['id']}: missing config artifact {artifact}", problems)
        if not path.is_file():
            continue
        raw = path.read_text(encoding="utf-8")
        if client.get("url_path"):
            _expect(
                client["url_path"] in raw,
                f"{client['id']}: {artifact} does not contain transport path "
                f"{client['url_path']}",
                problems,
            )
        # Comments may legitimately spell the documented ``reqlo_…`` hint;
        # only a literal key in an actual config value is a leak.
        non_comment = [
            line
            for line in raw.splitlines()
            if not line.lstrip().startswith(("#", "//"))
        ]
        _expect(
            conv["api_key_prefix"] not in "\n".join(non_comment),
            f"{client['id']}: {artifact} embeds a literal {conv['api_key_prefix']} key",
            problems,
        )
    return problems


_HEADING_RE = re.compile(r"^#{1,6} ", re.MULTILINE)
_FENCE_RE = re.compile(r"^```", re.MULTILINE)


def check_parity(files: dict[Path, str]) -> list[str]:
    """German/English pages must have identical headings and code-block counts."""
    problems: list[str] = []
    for client_id in CLIENT_IDS:
        de = files.get(DOCS_DIR / f"{client_id}.de.md", "")
        en = files.get(DOCS_DIR / f"{client_id}.md", "")
        if len(_HEADING_RE.findall(de)) != len(_HEADING_RE.findall(en)):
            problems.append(f"{client_id}: DE/EN heading count differs")
        if len(_FENCE_RE.findall(de)) != len(_FENCE_RE.findall(en)):
            problems.append(f"{client_id}: DE/EN code-block count differs")
    return problems


def plan_outputs(registry: dict[str, Any]) -> dict[Path, str]:
    registry["clients"] = [
        {**client, "__conventions": registry["conventions"]}
        for client in registry["clients"]
    ]
    files: dict[Path, str] = {}
    for client in registry["clients"]:
        files[DOCS_DIR / f"{client['id']}.md"] = render_client(client, lang="en")
        files[DOCS_DIR / f"{client['id']}.de.md"] = render_client(client, lang="de")
    files[DOCS_DIR / "README.md"] = render_matrix(registry, lang="en")
    files[DOCS_DIR / "README.de.md"] = render_matrix(registry, lang="de")
    return files


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit non-zero if artifacts are stale or invalid",
    )
    args = parser.parse_args(argv)

    registry = load_registry()
    problems = validate_artifacts(registry)
    files = plan_outputs(registry)
    problems += check_parity(files)

    stale: list[str] = []
    for path, content in files.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            stale.append(path.relative_to(REPO_ROOT).as_posix())

    if args.check:
        for problem in problems:
            print(f"ERROR: {problem}", file=sys.stderr)
        for path in stale:
            print(f"STALE: {path} (run scripts/clients/render.py)", file=sys.stderr)
        if problems or stale:
            return 1
        print(f"OK: {len(files)} client artifacts up to date")
        return 0

    if problems:
        for problem in problems:
            print(f"ERROR: {problem}", file=sys.stderr)
        return 1

    written = 0
    for path, content in files.items():
        if path.is_file() and path.read_text(encoding="utf-8") == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        written += 1
    print(f"wrote {written} of {len(files)} artifacts ({len(files) - written} unchanged)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
