# Generated by Django 4.2.30 on 2026-06-28 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_delete_baseline'),
        ('baseline', '0002_alter_baselinesnapshot_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baselinesnapshot',
            name='artifact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baseline_snapshots', to='persistence.artifact'),
        ),
    ]
