"""baseline — create ``bl_baseline_gate_waiver`` (GH-821).

leaf_id: COMP-BL-003 (BaselineStore extension)
req_id:  REQ-L2-BL-001, REQ-L2-AL-001

Adds the per-blocker waiver registry behind the per-finding exit from the
SE-Auditor baseline gate (issue #821). The table is new, so there is no data
migration and no backfill: an existing workspace simply has no waivers, i.e. the
gate keeps its previous fail-closed behaviour until someone explicitly grants
one. ``ck_baseline_waiver_reason_not_blank`` is the DB-level half of "a waiver
without a stated reason is not a governance record".

Companion migration ``0008_baseline_gate_waiver_rls`` installs the tenant
isolation policy this ``TenantScopedModel`` requires (REQ-L2-PL-010); the
coverage guard ``persistence/tests/test_rls_coverage.py`` fails without it.
"""

# Generated by Django 6.1.1 on 2026-09-15 22:26

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseline', '0006_baseline_snapshot_rls'),
        ('persistence', '0093_normalize_testcase_artifact_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineGateWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('rule_id', models.CharField(max_length=64)),
                ('finding_key', models.CharField(max_length=255)),
                ('artifact_ids', models.JSONField(blank=True, default=list)),
                ('scope', models.CharField(blank=True, default='', max_length=32)),
                ('scope_artifact_id', models.CharField(blank=True, default='', max_length=64)),
                ('reason', models.TextField()),
                ('granted_by', models.CharField(blank=True, default='', max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'bl_baseline_gate_waiver',
                'indexes': [models.Index(fields=['workspace_id', 'rule_id'], name='idx_baseline_waiver_ws_rule')],
                'constraints': [models.UniqueConstraint(fields=('workspace_id', 'finding_key'), name='uq_baseline_waiver_ws_finding'), models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='ck_baseline_waiver_reason_not_blank')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
