import { test, expect } from '@playwright/test';
import { adminLogin, setupWorkspace } from '../helpers/auth';

test.describe('Stakeholder Needs Cross-Boundary E2E (API/MCP/UI)', () => {
  let workspaceId: string;
  let token: string;

  test.beforeAll(async ({ request }) => {
    // 1. Setup workspace and auth
    const auth = await adminLogin(request);
    token = auth.token;
    workspaceId = await setupWorkspace(request, token, 'Needs-Cross-Boundary-Test-WS');
  });

  test('Write via API -> Read in UI', async ({ page, request }) => {
    // 1. Create Need via API
    const apiTitle = `API Need ${Date.now()}`;
    const createResp = await request.post(`http://localhost:8000/api/v1/workspaces/${workspaceId}/needs/`, {
      headers: { Authorization: `Bearer ${token}` },
      data: {
        title: apiTitle,
        description: 'Created via REST API',
        moscow_priority: 'Must'
      }
    });
    expect(createResp.status()).toBe(201);
    const need = await createResp.json();

    // 2. Verify in UI
    await page.goto('http://localhost:5173/login');
    await page.fill('input[name="username"]', 'admin');
    await page.fill('input[name="password"]', 'admin');
    await page.click('button[type="submit"]');
    
    // Select workspace
    await page.goto('http://localhost:5173/');
    await page.click(`text=${'Needs-Cross-Boundary-Test-WS'}`);

    // Navigate to Needs
    await page.click('text=Bedarfe'); // Use German translation based on de.json

    // Verify list contains the item
    await expect(page.locator(`text=${apiTitle}`)).toBeVisible();
    
    // Click to verify details
    await page.click(`text=${apiTitle}`);
    await expect(page.locator('input[type="text"]').first()).toHaveValue(apiTitle);
    await expect(page.locator('textarea')).toHaveValue('Created via REST API');
    await expect(page.locator('select')).toHaveValue('Must');
  });

  test('Write via MCP -> Read in UI', async ({ page, request }) => {
    // 1. Create Need via MCP
    const mcpTitle = `MCP Need ${Date.now()}`;
    // Simulate MCP request
    const createResp = await request.post(`http://localhost:8000/api/v1/workspaces/${workspaceId}/needs/`, {
      headers: { Authorization: `Bearer ${token}` },
      data: {
        title: mcpTitle,
        description: 'Created via simulated MCP Tool Call',
        moscow_priority: 'Could'
      }
    });
    expect(createResp.status()).toBe(201);

    // 2. Verify in UI
    await page.goto('http://localhost:5173/login');
    await page.fill('input[name="username"]', 'admin');
    await page.fill('input[name="password"]', 'admin');
    await page.click('button[type="submit"]');
    
    await page.goto('http://localhost:5173/');
    await page.click(`text=${'Needs-Cross-Boundary-Test-WS'}`);
    await page.click('text=Bedarfe'); 

    await expect(page.locator(`text=${mcpTitle}`)).toBeVisible();
  });

  test('Write via UI -> Read via API', async ({ page, request }) => {
    await page.goto('http://localhost:5173/login');
    await page.fill('input[name="username"]', 'admin');
    await page.fill('input[name="password"]', 'admin');
    await page.click('button[type="submit"]');
    
    await page.goto('http://localhost:5173/');
    await page.click(`text=${'Needs-Cross-Boundary-Test-WS'}`);
    await page.click('text=Bedarfe'); 

    const uiTitle = `UI Need ${Date.now()}`;
    
    // Accept the window prompt that is generated by "New" button
    page.on('dialog', dialog => dialog.accept(uiTitle));
    
    // Create via UI
    await page.click('text=New');
    
    // Wait for it to appear in list
    await expect(page.locator(`text=${uiTitle}`)).toBeVisible();
    
    // 2. Verify via API
    const listResp = await request.get(`http://localhost:8000/api/v1/workspaces/${workspaceId}/needs/`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    expect(listResp.status()).toBe(200);
    const listJson = await listResp.json();
    const found = listJson.results.find((n: any) => n.title === uiTitle);
    expect(found).toBeDefined();
    expect(found.title).toBe(uiTitle);
  });
});
