# Generated by Django 4.2.30 on 2026-06-25 08:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='apikey',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userrole',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
