# Generated by Django 4.2.30 on 2026-06-28 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_delete_baseline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_tenancy', '0003_item_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWorkspacePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('optional_artifact_visibility', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_preferences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='persistence.workspace')),
            ],
            options={
                'db_table': 'at_user_workspace_preference',
                'indexes': [models.Index(fields=['user', 'workspace'], name='idx_userpref_user_ws')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='userworkspacepreference',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'workspace'), name='uq_userpref_tenant_user_ws'),
        ),
    ]
