# Generated by Django 4.2.30 on 2026-07-18 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persistence', '0042_testcase_workflow_status'),
        ('auth_tenancy', '0004_userworkspacepreference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermissionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('permission_json', models.JSONField(default=dict)),
                ('enforcement_mode', models.CharField(choices=[('shadow', 'Shadow (legacy decides, new observed)'), ('authoritative', 'Authoritative (new decides)')], default='shadow', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'at_global_permission_definition',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspacePermissionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('permission_json', models.JSONField(default=dict)),
                ('is_customized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_definitions', to='auth_tenancy.globalpermissiondefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_definitions', to='persistence.workspace')),
            ],
            options={
                'db_table': 'at_workspace_permission_definition',
                'indexes': [models.Index(fields=['workspace'], name='idx_ws_perm_def_workspace')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacepermissiondefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'workspace'), name='uq_ws_perm_def_tenant_ws'),
        ),
        migrations.AddConstraint(
            model_name='globalpermissiondefinition',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_global_perm_def_tenant'),
        ),
        migrations.CreateModel(
            name='PermissionDecisionMismatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('subject_identifier', models.CharField(max_length=255)),
                ('capability', models.CharField(max_length=128)),
                ('artifact_id', models.UUIDField(blank=True, null=True)),
                ('legacy_decision', models.BooleanField()),
                ('new_decision', models.BooleanField()),
                ('context_json', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_decision_mismatches', to='persistence.workspace')),
            ],
            options={
                'db_table': 'at_permission_decision_mismatch',
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='idx_perm_mismatch_ws_time')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
