# Generated by Django 6.1.1 on 2026-09-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0012_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='agent_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='principal_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('read', 'Read'), ('write', 'Write')], default='write', max_length=16),
        ),
        migrations.AddField(
            model_name='apikey',
            name='workspace_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
