# Generated by Django 6.1.1 on 2026-09-16 06:32
"""auth_tenancy — granular API-key scopes (#865).

Widens ``ApiKey.scope``'s choices with the canonical tiers ``read_only``,
``author`` and ``admin``. Choices are validation metadata only — no column or
constraint changes, so every existing row stays valid: the two legacy values
keep their exact previous meaning (``read`` = READ_ONLY tier, ``write`` = the
widest, legacy tier). No data migration is needed or wanted.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0014_user_notification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='scope',
            field=models.CharField(choices=[('read', 'Read (legacy alias of read_only)'), ('write', 'Write (legacy alias of admin)'), ('read_only', 'Read-only'), ('author', 'Author (content writes only)'), ('admin', 'Admin (all operations)')], default='write', max_length=16),
        ),
    ]
