# Generated by Django 6.1.1 on 2026-10-04 18:11
"""auth_tenancy — DB-backed admin brute-force lockout (issue #1135).

Creates ``at_admin_login_lockout``, keyed by ``(client_ip, username_digest)``.
The model is a GLOBAL ``AuditableModel`` (no ``tenant`` FK) because it is written
on the pre-authentication admin login path where no tenant context exists — the
same precedent as ``persistence.User``/``Tenant``. It is therefore NOT covered by
the ``TenantScopedModel`` RLS coverage gate and needs no policy migration.
"""

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0015_alter_apikey_scope'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginLockout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('client_ip', models.GenericIPAddressField()),
                ('username_digest', models.CharField(max_length=32)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('first_failure_at', models.DateTimeField()),
                ('last_failure_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'at_admin_login_lockout',
                'indexes': [models.Index(fields=['last_failure_at'], name='idx_admin_lockout_last')],
                'constraints': [models.UniqueConstraint(fields=('client_ip', 'username_digest'), name='uq_admin_lockout_ip_user')],
            },
        ),
    ]
