# Generated by Django 6.1.1 on 2026-10-04 19:03
"""auth_tenancy — index for the admin-lockout expiry cleanup (issue #1135).

Adds ``idx_admin_lockout_locked_until`` so the opportunistic cleanup predicate
``locked_until__lt`` is indexed (F6). No column change; ``at_admin_login_lockout``
is a global (non-tenant-scoped) table and needs no RLS policy.
"""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0016_admin_login_lockout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='adminloginlockout',
            index=models.Index(fields=['locked_until'], name='idx_admin_lockout_locked_until'),
        ),
    ]
