# Generated by Django 6.1.1 on 2026-10-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0017_admin_lockout_expiry_index'),
        ('auth_tenancy', '0017_preauth_staged_rls'),
    ]

    operations = [
    ]
