# Generated by Django 6.1.1 on 2026-10-07 00:00
"""auth_tenancy — per-user display preferences (Issue #1096).

Creates ``at_user_display_preference``: one row per user holding the account's
UI display flags. First and currently only field is ``show_readable_ids``.

The model is a ``TenantScopedModel`` because the serving route
(``/api/v1/users/me/display-preferences/``) is classified ``ResourceScope.TENANT``
like the other ``users/me/**`` routes, so the row carries the standard tenant
column and is closed by the RLS policy in ``0020_user_display_preference_rls``
(REQ-L2-PL-010).

PROPOSAL — authored manually for human review, NOT applied (no ``makemigrations``
/ ``migrate`` run). See the hand-off report for the approval gate.
"""

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0018_merge_auth_tenancy_leaves'),
        ('persistence', '0106_alter_llmsettings_provider_azure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDisplayPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('show_readable_ids', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='display_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'at_user_display_preference',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
