# Generated by Django 6.1.1 on 2026-09-06 22:18

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0079_drop_glossary_term_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalAttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('item_type', models.CharField(max_length=128)),
                ('preset', models.CharField(choices=[('minimal', 'Minimal'), ('standard', 'Standard'), ('extended', 'Extended')], max_length=32)),
                ('definition_json', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'ad_global_definition',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceAttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('item_type', models.CharField(max_length=128)),
                ('preset', models.CharField(choices=[('minimal', 'Minimal'), ('standard', 'Standard'), ('extended', 'Extended')], max_length=32)),
                ('definition_json', models.JSONField(default=dict)),
                ('is_customized', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_definitions', to='attribute_definitions.globalattributedefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'ad_workspace_definition',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='globalattributedefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'item_type', 'preset'), name='uq_ad_global_def_tenant_type_preset'),
        ),
        migrations.AddIndex(
            model_name='workspaceattributedefinition',
            index=models.Index(fields=['workspace_id', 'item_type'], name='idx_ad_ws_def_ws_type'),
        ),
        migrations.AddConstraint(
            model_name='workspaceattributedefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'workspace_id', 'item_type'), name='uq_ad_ws_def_tenant_ws_type'),
        ),
    ]
