# Generated by Django 4.2.30 on 2026-06-25 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_rls_policies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='architectureelement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='artifact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='auditlogentry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='baseline',
            options={},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tracelink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowdefinition',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowstate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workspace',
            options={},
        ),
        migrations.AlterModelManagers(
            name='architectureelement',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='artifact',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='auditlogentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='baseline',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='requirement',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='testcase',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tracelink',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workflowdefinition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workflowstate',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='workspace',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='architectureelement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='tracelink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='workflowdefinition',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='workflowstate',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
    ]
