# Generated by Django 4.2.30 on 2026-06-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0007_testrun_testrunresult'),
        ('admin', '0003_logentry_add_action_flag_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.'),
        ),
        # AUTH_USER_MODEL changed from auth.User (int PK) to persistence.User
        # (UUID PK). The django_admin_log.user_id column was created as integer
        # with a FK to auth_user(id). Must drop old FK, alter type, add new FK.
        migrations.RunSQL(
            sql=[
                "ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;",
                "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE uuid USING user_id::text::uuid;",
                "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_fk_pl_user FOREIGN KEY (user_id) REFERENCES pl_user(id) DEFERRABLE INITIALLY DEFERRED;",
            ],
            reverse_sql=[
                "ALTER TABLE django_admin_log DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fk_pl_user;",
                "ALTER TABLE django_admin_log ALTER COLUMN user_id TYPE integer USING user_id::text::integer;",
                "ALTER TABLE django_admin_log ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED;",
            ],
        ),
    ]
