# Generated by Django 4.2.30 on 2026-06-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0010_rls_item_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Baseline',
        ),
    ]
