# Generated by Django 4.2.30 on 2026-07-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0011_delete_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='architectureelement',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='persistence.architectureelement'),
        ),
    ]
