# Generated by Django 4.2.30 on 2026-07-04 12:00
"""
Migration: Phase 1 — SE Mask Standardization (REQ-L1-058 through REQ-L3-RF004-004)

Adds type-dependent fields to Requirement and ArchitectureElement:
- Requirement: type, moscow_priority, complexity_fibonacci, verification_method, uid
- ArchitectureElement: asil_level, make_or_buy, uid
- New model: AttributeVisibilityConfig for admin configuration
- Backfill: Requirement.type defaults to 'SyReq'
"""

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0012_add_parent_id_to_architecture_element'),
    ]

    operations = [
        # --------------------------------------------------------------------------
        # Phase 1.1: Add new columns to Requirement
        # --------------------------------------------------------------------------
        migrations.AddField(
            model_name='requirement',
            name='type',
            field=models.CharField(
                max_length=64,
                default='SyReq',
                choices=[
                    ('StReq', 'Stakeholder Requirement'),
                    ('SyReq', 'System Requirement'),
                    ('UseCase', 'Use Case'),
                    ('FeatureReq', 'Feature Requirement'),
                ],
                help_text='Requirement classification per REQ-L3-RF003-005',
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='requirement',
            name='moscow_priority',
            field=models.CharField(
                max_length=16,
                null=True,
                blank=True,
                choices=[
                    ('Must', 'Must Have'),
                    ('Should', 'Should Have'),
                    ('Could', 'Could Have'),
                    ('Won\'t', 'Won\'t Have'),
                ],
                help_text='MoSCoW priority (visible only for StReq)',
            ),
        ),

        migrations.AddField(
            model_name='requirement',
            name='complexity_fibonacci',
            field=models.IntegerField(
                null=True,
                blank=True,
                choices=[
                    (1, '1'),
                    (2, '2'),
                    (3, '3'),
                    (5, '5'),
                    (8, '8'),
                    (13, '13'),
                    (21, '21'),
                ],
                help_text='Complexity via Fibonacci scale (visible only for SyReq)',
            ),
        ),

        migrations.AddField(
            model_name='requirement',
            name='verification_method',
            field=models.CharField(
                max_length=128,
                null=True,
                blank=True,
                choices=[
                    ('Test', 'Test'),
                    ('Review', 'Review'),
                    ('Analysis', 'Analysis'),
                    ('Inspection', 'Inspection'),
                ],
                help_text='Verification method (visible only for SyReq)',
            ),
        ),

        migrations.AddField(
            model_name='requirement',
            name='uid',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                unique=False,
                help_text='Unique identifier (read-only, auto-generated)',
            ),
        ),

        # --------------------------------------------------------------------------
        # Phase 1.2: Add new columns to ArchitectureElement
        # --------------------------------------------------------------------------
        migrations.AddField(
            model_name='architectureelement',
            name='asil_level',
            field=models.CharField(
                max_length=16,
                null=True,
                blank=True,
                choices=[
                    ('QM', 'QM'),
                    ('A', 'ASIL A'),
                    ('B', 'ASIL B'),
                    ('C', 'ASIL C'),
                    ('D', 'ASIL D'),
                ],
                help_text='ASIL level per REQ-L3-RF004-004',
            ),
        ),

        migrations.AddField(
            model_name='architectureelement',
            name='make_or_buy',
            field=models.CharField(
                max_length=32,
                null=True,
                blank=True,
                choices=[
                    ('Make', 'Make'),
                    ('Buy', 'Buy'),
                    ('Reuse', 'Reuse'),
                ],
                help_text='Make-or-Buy decision per REQ-L3-RF004-004',
            ),
        ),

        migrations.AddField(
            model_name='architectureelement',
            name='uid',
            field=models.CharField(
                max_length=64,
                null=True,
                blank=True,
                unique=False,
                help_text='Unique identifier (read-only, auto-generated)',
            ),
        ),

        # --------------------------------------------------------------------------
        # Phase 1.3: Create AttributeVisibilityConfig model
        # --------------------------------------------------------------------------
        migrations.CreateModel(
            name='AttributeVisibilityConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=64, help_text='Target entity type (e.g., Requirement, ArchitectureElement)')),
                ('attribute_name', models.CharField(max_length=128, help_text='Field name (e.g., moscow_priority)')),
                ('is_visible', models.BooleanField(default=True, help_text='Show/hide toggle')),
                ('is_required', models.BooleanField(default=False, help_text='Mark as required in forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.user')),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.user')),
                ('version', models.IntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attribute_visibility_configs', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_attribute_visibility_config',
            },
        ),

        # --------------------------------------------------------------------------
        # Phase 1.4: Add indexes for performance (REQ-L3-PL005-001)
        # --------------------------------------------------------------------------
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['type'], name='idx_requirement_type_btree'),
        ),

        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['uid'], name='idx_requirement_uid_btree'),
        ),

        migrations.AddIndex(
            model_name='architectureelement',
            index=models.Index(fields=['asil_level'], name='idx_arch_elem_asil_btree'),
        ),

        migrations.AddIndex(
            model_name='architectureelement',
            index=models.Index(fields=['make_or_buy'], name='idx_arch_elem_makebuy_btree'),
        ),

        migrations.AddIndex(
            model_name='architectureelement',
            index=models.Index(fields=['uid'], name='idx_arch_elem_uid_btree'),
        ),

        migrations.AddIndex(
            model_name='attributevisibilityconfig',
            index=models.Index(fields=['tenant', 'entity_type'], name='idx_attrvisib_tenant_type'),
        ),

        migrations.AddConstraint(
            model_name='attributevisibilityconfig',
            constraint=models.UniqueConstraint(
                fields=['tenant', 'entity_type', 'attribute_name'],
                name='uq_attrvisib_tenant_entity_attr',
            ),
        ),
    ]
