# Generated by Django 4.2.30 on 2026-07-04 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0013_add_se_mask_fields'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attributevisibilityconfig',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='architectureelement',
            name='idx_arch_elem_asil_btree',
        ),
        migrations.RemoveIndex(
            model_name='architectureelement',
            name='idx_arch_elem_makebuy_btree',
        ),
        migrations.RemoveIndex(
            model_name='architectureelement',
            name='idx_arch_elem_uid_btree',
        ),
        migrations.RemoveIndex(
            model_name='requirement',
            name='idx_requirement_type_btree',
        ),
        migrations.RemoveIndex(
            model_name='requirement',
            name='idx_requirement_uid_btree',
        ),
        migrations.AlterField(
            model_name='architectureelement',
            name='asil_level',
            field=models.CharField(blank=True, choices=[('QM', 'QM (not ASIL)'), ('A', 'ASIL A'), ('B', 'ASIL B'), ('C', 'ASIL C'), ('D', 'ASIL D')], help_text='ASIL level (QM, A, B, C, D) per REQ-L3-RF004-004', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='attributevisibilityconfig',
            name='attribute_name',
            field=models.CharField(help_text="Field name (e.g., 'moscow_priority', 'asil_level')", max_length=128),
        ),
        migrations.AlterField(
            model_name='attributevisibilityconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Audit: who created this config', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attributevisibilityconfig',
            name='entity_type',
            field=models.CharField(help_text="Target entity type (e.g., 'Requirement', 'ArchitectureElement')", max_length=64),
        ),
        migrations.AlterField(
            model_name='attributevisibilityconfig',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Show/hide toggle for frontend'),
        ),
        migrations.AlterField(
            model_name='attributevisibilityconfig',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='Audit: who last modified this config', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attributevisibilityconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='attributevisibilityconfig',
            name='version',
            field=models.IntegerField(default=1, help_text='Audit: version counter'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='complexity_fibonacci',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (5, 'Five'), (8, 'Eight'), (13, 'Thirteen'), (21, 'Twenty One')], help_text='Complexity via Fibonacci scale (visible only for SyReq)', null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('StReq', 'Stakeholder Requirement'), ('SyReq', 'System Requirement'), ('UseCase', 'Use Case'), ('FeatureReq', 'Feature Requirement')], default='SyReq', help_text='Requirement classification (StReq, SyReq, UseCase, FeatureReq)', max_length=64),
        ),
    ]
