# Generated by Django 4.2.30 on 2026-07-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0015_glossaryterm_glossarytermversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='decomposition_link_type',
            field=models.CharField(default='parent-child', help_text='Default link type used when decomposing requirements.', max_length=50),
        ),
    ]
