# Generated by Django 4.2.30 on 2026-07-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0016_workspace_decomposition_link_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glossaryterm',
            name='uq_glossary_workspace_term',
        ),
        migrations.AddField(
            model_name='architectureelement',
            name='suspect',
            field=models.BooleanField(default=False, help_text='SN-30: Indicates if this element needs review due to upstream changes.'),
        ),
        migrations.AddField(
            model_name='requirement',
            name='suspect',
            field=models.BooleanField(default=False, help_text='SN-30: Indicates if this requirement needs review due to upstream changes.'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='suspect',
            field=models.BooleanField(default=False, help_text='SN-30: Indicates if this test case needs review due to upstream changes.'),
        ),
        migrations.AlterField(
            model_name='glossaryterm',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='glossarytermversion',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='glossarytermversion',
            name='term_version',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='glossaryterm',
            unique_together={('workspace', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='glossarytermversion',
            unique_together={('term_fk', 'term_version')},
        ),
    ]
