# Generated by Django 4.2.30 on 2026-07-04 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0017_remove_glossaryterm_uq_glossary_workspace_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='parent_workspace',
            field=models.ForeignKey(blank=True, help_text='SN-33: Source workspace this sandbox was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandboxes', to='persistence.workspace'),
        ),
    ]
