# Generated by Django 4.2.30 on 2026-07-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0018_workspace_parent_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossaryterm',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossary_terms', to='persistence.workspace'),
        ),
    ]
