# Generated by Django 4.2.30 on 2026-07-05 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0019_alter_glossaryterm_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='moscow_priority',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='type',
            field=models.CharField(choices=[('SyReq', 'System Requirement'), ('UseCase', 'Use Case'), ('FeatureReq', 'Feature Requirement')], default='SyReq', help_text='Requirement classification (SyReq, UseCase, FeatureReq)', max_length=64),
        ),
        migrations.CreateModel(
            name='StakeholderNeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='draft', max_length=64)),
                ('moscow_priority', models.CharField(blank=True, choices=[('Must', 'Must Have'), ('Should', 'Should Have'), ('Could', 'Could Have'), ("Won't", "Won't Have")], help_text='MoSCoW priority', max_length=16, null=True)),
                ('uid', models.CharField(blank=True, help_text='Unique identifier (read-only, auto-generated)', max_length=64, null=True)),
                ('suspect', models.BooleanField(default=False, help_text='SN-30: Indicates if this need requires review due to upstream changes.')),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_need', to='persistence.artifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_stakeholder_need',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
