# Generated by Django 4.2.30 on 2026-07-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0020_remove_requirement_moscow_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='ai_prompts',
            field=models.JSONField(blank=True, default=dict, help_text='SN-56: Configurable AI derivation prompts per level.'),
        ),
    ]
