# Generated by Django 4.2.30 on 2026-07-11 14:19
#
# REQ-L2-LLM-001 — LlmSettings model (tenant-scoped singleton).
#
# Operation order matters:
#   1. CreateModel + unique constraint on tenant.
#   2. Enable + FORCE RLS on ``pl_llm_settings`` (defense-in-depth, mirrors
#      0003_rls_policies.py / 0010_rls_item_permission.py).
#
# This migration originally seeded a default ``provider="mock"`` row for every
# existing tenant (between the two steps above, so the insert ran before the
# tenant-isolation policy could reject it). That seeding step was REMOVED —
# see issue #276 and 0056_unseed_default_llm_settings.py, which deletes the
# rows it created on already-migrated deployments.
#
# Why: ``llm_adapter.providers._apply_db_settings`` gives an existing
# LlmSettings row unconditional precedence over the environment. A seeded row
# therefore pinned the tenant to the mock provider permanently and turned the
# deployment's ``LLM_PROVIDER`` into a silent no-op — AI features returned
# mock placeholders with no error anywhere. Row existence must mean "an admin
# explicitly configured this tenant"; without a row the environment is the
# fallback, which is the documented architecture.
#
# Dropping the operation is safe for deployments that already applied this
# migration: Django records only the migration *name* in ``django_migrations``
# and never re-runs applied operations. Fresh installs are unaffected in
# practice either way — on an empty database no tenant exists yet when this
# migration runs (the base tenant is created afterwards by the post_migrate
# self-init, application/self_init.py), so the seed matched zero rows there.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


_TABLE = "pl_llm_settings"
_POLICY = f"{_TABLE}_tenant_isolation"

_ENABLE_RLS_SQL = (
    f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY;\n"
    f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY;\n"
    f"CREATE POLICY {_POLICY} ON {_TABLE}\n"
    f"    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)\n"
    f"    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);"
)

_DISABLE_RLS_SQL = (
    f"DROP POLICY IF EXISTS {_POLICY} ON {_TABLE};\n"
    f"ALTER TABLE {_TABLE} NO FORCE ROW LEVEL SECURITY;\n"
    f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY;"
)


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0025_tracelink_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('ollama', 'Ollama'), ('mock', 'Mock')], default='mock', help_text='Active LLM provider. Defaults to the credential-free mock.', max_length=32)),
                ('base_url', models.URLField(blank=True, default='', help_text='Optional base URL override (e.g. for a local Ollama server).')),
                ('api_key', models.CharField(blank=True, default='', help_text='Provider API key. Never returned via the REST API.', max_length=512)),
                ('model_name', models.CharField(blank=True, default='', help_text="Free-text model identifier (e.g. 'claude-3-opus-20240229').", max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_llm_settings',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='llmsettings',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_llm_settings_tenant'),
        ),
        migrations.RunSQL(sql=_ENABLE_RLS_SQL, reverse_sql=_DISABLE_RLS_SQL),
    ]
