# Generated by Django 4.2.30 on 2026-07-11 14:19
#
# REQ-L2-LLM-001 — LlmSettings model (tenant-scoped singleton).
#
# Operation order matters:
#   1. CreateModel + unique constraint on tenant.
#   2. Seed a default (provider=mock) row for every existing tenant — this runs
#      BEFORE Row-Level Security is enabled so the insert is not rejected by the
#      tenant-isolation policy (which would match no rows without an active
#      ``app.current_tenant`` setting during migration).
#   3. Enable + FORCE RLS on ``pl_llm_settings`` (defense-in-depth, mirrors
#      0003_rls_policies.py / 0010_rls_item_permission.py).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


_TABLE = "pl_llm_settings"
_POLICY = f"{_TABLE}_tenant_isolation"

_ENABLE_RLS_SQL = (
    f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY;\n"
    f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY;\n"
    f"CREATE POLICY {_POLICY} ON {_TABLE}\n"
    f"    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)\n"
    f"    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);"
)

_DISABLE_RLS_SQL = (
    f"DROP POLICY IF EXISTS {_POLICY} ON {_TABLE};\n"
    f"ALTER TABLE {_TABLE} NO FORCE ROW LEVEL SECURITY;\n"
    f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY;"
)


def _seed_defaults(apps, schema_editor):
    """Create a default mock LlmSettings row for every existing tenant."""
    Tenant = apps.get_model("persistence", "Tenant")
    LlmSettings = apps.get_model("persistence", "LlmSettings")
    for tenant in Tenant.objects.all():
        LlmSettings.objects.get_or_create(
            tenant=tenant, defaults={"provider": "mock"}
        )


def _unseed_defaults(apps, schema_editor):
    """Reverse: drop all seeded rows (table is dropped by CreateModel reverse)."""
    LlmSettings = apps.get_model("persistence", "LlmSettings")
    LlmSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0025_tracelink_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('ollama', 'Ollama'), ('mock', 'Mock')], default='mock', help_text='Active LLM provider. Defaults to the credential-free mock.', max_length=32)),
                ('base_url', models.URLField(blank=True, default='', help_text='Optional base URL override (e.g. for a local Ollama server).')),
                ('api_key', models.CharField(blank=True, default='', help_text='Provider API key. Never returned via the REST API.', max_length=512)),
                ('model_name', models.CharField(blank=True, default='', help_text="Free-text model identifier (e.g. 'claude-3-opus-20240229').", max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_llm_settings',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='llmsettings',
            constraint=models.UniqueConstraint(fields=('tenant',), name='uq_llm_settings_tenant'),
        ),
        migrations.RunPython(_seed_defaults, _unseed_defaults),
        migrations.RunSQL(sql=_ENABLE_RLS_SQL, reverse_sql=_DISABLE_RLS_SQL),
    ]
