# Generated by Django 4.2.30 on 2026-07-13 06:16

# REQ-006 (D5): drop the ElementType choices restriction on
# ArchitectureElement.element_type. Django choices are Python-level state
# only (no DB constraint), so this is a state-only migration — no data
# migration or column change is required.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0031_add_user_name_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectureelement',
            name='element_type',
            field=models.CharField(blank=True, default='component', max_length=64),
        ),
    ]
