# Generated by Django 4.2.30 on 2026-07-13 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0032_alter_architectureelement_element_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(help_text='Human-readable field label, unique within the workspace.', max_length=128)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('dropdown', 'Dropdown')], default='text', help_text='Data type: text, number or dropdown.', max_length=16)),
                ('is_required', models.BooleanField(default=False, help_text='Whether a value must be provided on the artifact form.')),
                ('options', models.JSONField(blank=True, default=list, help_text='Dropdown options as a list of strings. Empty for text/number fields; required (non-empty) for dropdown fields.')),
                ('order', models.IntegerField(default=0, help_text='Display order of the field in artifact forms (ascending).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_definitions', to='persistence.workspace')),
            ],
            options={
                'db_table': 'pl_custom_field_definition',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('value', models.TextField(blank=True, default='', help_text='Stored value (string representation).')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='persistence.artifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='persistence.customfielddefinition')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_custom_field_value',
                'indexes': [models.Index(fields=['artifact'], name='idx_customfieldvalue_artifact')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('definition', 'artifact'), name='uq_customfieldvalue_definition_artifact'),
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['workspace'], name='idx_customfielddef_workspace'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uq_customfielddef_workspace_name'),
        ),
    ]
