# Generated by Django 4.2.30 on 2026-07-14 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0033_customfielddefinition_customfieldvalue_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='architectureelement',
            index=models.Index(fields=['tenant', 'element_type'], name='idx_archelem_tnt_type'),
        ),
        migrations.AddIndex(
            model_name='architectureelement',
            index=models.Index(fields=['tenant', 'lifecycle_status'], name='idx_archelem_tnt_lifecyc'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['tenant', 'workspace'], name='idx_artifact_tnt_ws'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['tenant', 'artifact_type'], name='idx_artifact_tnt_type'),
        ),
        migrations.AddIndex(
            model_name='artifact',
            index=models.Index(fields=['tenant', 'workspace', 'artifact_type'], name='idx_artifact_tnt_ws_type'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', 'status'], name='idx_req_tnt_status'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', 'lifecycle_status'], name='idx_req_tnt_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='stakeholderneed',
            index=models.Index(fields=['tenant', 'status'], name='idx_sn_tnt_status'),
        ),
        migrations.AddIndex(
            model_name='stakeholderneed',
            index=models.Index(fields=['tenant', 'lifecycle_status'], name='idx_sn_tnt_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['tenant', 'workspace'], name='idx_testrun_tnt_ws'),
        ),
        migrations.AddIndex(
            model_name='testrun',
            index=models.Index(fields=['tenant', 'status'], name='idx_testrun_tnt_status'),
        ),
    ]
