# Generated by Django 4.2.30 on 2026-07-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0037_encrypt_llm_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='default_link_type',
            field=models.CharField(default='derives-from', help_text='Link type pre-selected when creating a new trace link.', max_length=50),
        ),
    ]
