# Generated by Django 4.2.30 on 2026-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0041_add_testcase_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Approved', 'Approved'), ('Deprecated', 'Deprecated')], default='Draft', max_length=32),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['status'], name='idx_testcase_status'),
        ),
    ]
