# Generated by Django 4.2.30 on 2026-07-25 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0045_prompt_template_versioning_cleanup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('mode', models.CharField(choices=[('auto', 'auto'), ('review_changes', 'review_changes'), ('review_all', 'review_all'), ('review_high_risk', 'review_high_risk')], default='auto', help_text='auto | review_changes | review_all | review_high_risk.', max_length=32)),
                ('min_confidence', models.FloatField(default=0.7, help_text='Threshold used only by review_high_risk mode.')),
                ('workspace_id', models.UUIDField(blank=True, help_text='Workspace override scope. NULL means tenant-wide default.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_review_policy',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='reviewpolicy',
            constraint=models.UniqueConstraint(fields=('tenant', 'workspace_id'), name='uq_review_policy_scope'),
        ),
    ]
