# Generated by Django 4.2.30 on 2026-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0046_add_review_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='acceptance_criteria',
            field=models.TextField(blank=True, default='', help_text='#43: Acceptance criteria describing when the requirement is fulfilled.'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['tenant', 'uid'], name='idx_req_tnt_uid'),
        ),
    ]
