# Generated by Django 4.2.30 on 2026-07-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0051_user_username_ci_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='goals_ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='goals_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
