# Generated by Django 4.2.30 on 2026-07-31 16:14
"""
#133: uid was only unique at the application layer (check-then-insert in
RequirementService._assert_uid_unique_in_workspace), which is race-prone
under concurrent creates. This migration:

1. Adds a denormalized `workspace` FK to Requirement (it previously had no
   direct workspace column — only via artifact.workspace) so a workspace-
   scoped DB constraint can be expressed at all.
2. Backfills `workspace` from the existing `artifact.workspace_id` for every
   row (RunPython — a plain AddField cannot populate from a joined table).
3. Deduplicates any pre-existing `(workspace, uid)` collision *before* the
   constraint is added: deterministic ordering (created_at, id) keeps the
   oldest row's uid untouched; later rows get a ` (n)` suffix. Renames only,
   never deletes; reverse is a documented no-op (mirrors the pattern used for
   `uq_workspace_tenant_name`, issue #127).
4. Adds the partial UniqueConstraint (uid IS NOT NULL AND uid != '') on
   (workspace, uid) as the DB-level, race-free authority. Scoped to
   workspace, not tenant, because ReqIF import legitimately copies the same
   identifier into a different workspace of the same tenant (see
   application/tests/test_reqif_import_service.py::
   TestReqifImportUpsertCollisions).
"""
from django.db import migrations, models
import django.db.models.deletion


def _backfill_workspace(apps, schema_editor):
    Requirement = apps.get_model("persistence", "Requirement")
    Artifact = apps.get_model("persistence", "Artifact")
    # QuerySet.update() rejects a joined-field F() reference directly, so a
    # correlated Subquery is used instead — still a single UPDATE statement,
    # no per-row Python.
    Requirement.objects.filter(workspace__isnull=True).update(
        workspace=models.Subquery(
            Artifact.objects.filter(id=models.OuterRef("artifact_id")).values(
                "workspace_id"
            )[:1]
        )
    )


def _dedupe_uid_collisions(apps, schema_editor):
    """Rename later duplicates of an existing (workspace, uid) collision.

    Only touches rows with a non-null, non-blank uid (the constraint is
    partial on that condition too). Deterministic (created_at, id) ordering:
    the oldest row keeps its uid untouched.
    """
    Requirement = apps.get_model("persistence", "Requirement")

    qs = (
        Requirement.objects.exclude(uid=None)
        .exclude(uid="")
        .order_by("workspace_id", "uid", "created_at", "id")
    )

    seen: dict[tuple, str] = {}
    for req in qs.iterator():
        key = (req.workspace_id, req.uid)
        if key not in seen:
            seen[key] = req.uid
            continue

        base_uid = seen[key]
        taken = {
            u
            for u in Requirement.objects.filter(
                workspace_id=req.workspace_id
            ).values_list("uid", flat=True)
        }
        suffix = 2
        # max_length=64 on Requirement.uid — cap the renamed value to fit.
        while True:
            candidate = f"{base_uid} ({suffix})"
            if len(candidate) > 64:
                candidate = candidate[:64]
            if candidate not in taken:
                break
            suffix += 1

        req.uid = candidate
        req.save(update_fields=["uid"])
        taken.add(candidate)


def _noop_reverse(apps, schema_editor):
    """Deliberate no-op: undoing the rename would re-introduce ambiguous
    duplicate uids, which is never desirable."""


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0052_workspace_goals_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='#133: denormalized copy of artifact.workspace_id, kept in sync by RequirementService/reqif_import_service/ImportService on create. Exists solely to back a DB-level UniqueConstraint on (workspace, uid) — Requirement otherwise has no direct workspace column and uid uniqueness was only enforced at the application layer (check-then-insert), which is race-prone under concurrent creates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='persistence.workspace'),
        ),
        migrations.RunPython(_backfill_workspace, migrations.RunPython.noop),
        migrations.RunPython(_dedupe_uid_collisions, _noop_reverse),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('uid', None), _negated=True), models.Q(('uid', ''), _negated=True)), fields=('workspace', 'uid'), name='uq_requirement_workspace_uid'),
        ),
    ]
