# Generated by Django 4.2.30 on 2026-07-31 12:59

from django.db import migrations, models
import persistence.custom_fields
import persistence.role_permissions


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0053_data_model_medium_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, help_text='REQ-L2-AS-037: User-defined custom attributes as a flat key-value map. Keys: strings. Values: str, int, float, bool, or null. A GIN index (pl_artifact_custom_fields_gin) backs JSONB queries.', null=True, validators=[persistence.custom_fields.validate_custom_fields]),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Issue #128: RBAC permission map, {"<key>": true | false | ["<scope>", ...]}. Validated on save() — arbitrary/nested JSON is rejected.', validators=[persistence.role_permissions.validate_role_permissions]),
        ),
    ]
