# Generated by Django 4.2.30 on 2026-08-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0056_unseed_default_llm_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmsettings',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'OpenAI'), ('ollama', 'Ollama'), ('opencode_go', 'OpenCode Go'), ('mock', 'Mock')], default='mock', help_text='Active LLM provider. Defaults to the credential-free mock.', max_length=32),
        ),
    ]
