# Generated by Django 4.2.30 on 2026-08-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0057_alter_llmsettings_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Issue #362: optional human-readable workspace description.'),
        ),
    ]
