# Generated by Django 5.2.17 on 2026-08-24 21:14

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0065_alter_interviewsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='session_kind',
            field=models.CharField(choices=[('single', 'Single artifact type'), ('multi', 'Multi-artifact discovery')], default='single', help_text="Interview axis: 'single' drives one typed artifact via the classic protocol; 'multi' lets the LLM propose several possibly different-typed artifacts with provenance in InterviewSessionArtifact.", max_length=16),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='artifact_type',
            field=models.CharField(blank=True, help_text='Which interview protocol applies (PascalCase, matches Artifact.artifact_type). NULL only for multi-artifact discovery sessions, which are not bound to a single protocol.', max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='InterviewSessionArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('artifact_type', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artifact', models.ForeignKey(help_text='Artifact created by the session (any in-scope artifact_type).', on_delete=django.db.models.deletion.CASCADE, related_name='interview_provenance', to='persistence.artifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Multi-mode interview session that created this artifact.', on_delete=django.db.models.deletion.CASCADE, related_name='created_artifacts', to='persistence.interviewsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_interview_session_artifact',
                'indexes': [models.Index(fields=['artifact'], name='idx_iview_artifact')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
