# Generated by Django 6.1 on 2026-09-04 19:39
#
# Datenmodell-Konsolidierung Task 12: drops the denormalized `status` mirror
# columns on Requirement/StakeholderNeed/TestCase/InterviewSession.
#
# Explicit extra dependencies on workflow.0003/0005/0014: those RunPython
# data migrations read/write `.status` on historical apps.get_model()
# snapshots of Requirement/StakeholderNeed/TestCase. Without an explicit edge
# here, Django's migration-plan topological sort is free to place this
# migration *before* them on a fresh `migrate` from zero (nothing otherwise
# orders a `persistence`-only migration relative to a `workflow` migration
# whose own declared dependency is an *earlier* persistence migration) --
# confirmed by an actual `migrate` run: without this, workflow.0014 crashed
# with `FieldError: Cannot resolve keyword 'status' into field` because the
# field was already gone in its historical model state. These edges force
# this migration to run strictly after every migration that still needs the
# column.
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0069_align_embedding_dimensions'),
        ('workflow', '0003_reconcile_status_mirror'),
        ('workflow', '0005_backfill_entity_item_states'),
        ('workflow', '0014_testcase_status_lowercase'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='interviewsession',
            name='idx_iview_ws_status',
        ),
        migrations.RemoveIndex(
            model_name='requirement',
            name='idx_req_tnt_status',
        ),
        migrations.RemoveIndex(
            model_name='stakeholderneed',
            name='idx_sn_tnt_status',
        ),
        migrations.RemoveIndex(
            model_name='testcase',
            name='idx_testcase_status',
        ),
        migrations.RemoveField(
            model_name='interviewsession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stakeholderneed',
            name='status',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='status',
        ),
    ]
