# Generated by Django 6.1 on 2026-09-05 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0071_adopt_layer2_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_request', to='persistence.artifact'),
        ),
        migrations.AddField(
            model_name='glossaryterm',
            name='artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glossary_term', to='persistence.artifact'),
        ),
    ]
