# Generated by Django 6.1 on 2026-09-06 00:16

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0075_drop_entity_lifecycle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('revision', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict, help_text='Full field snapshot of the artifact at this revision.')),
                ('change_reason', models.TextField(blank=True, default='')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='persistence.artifact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_artifact_version',
                'indexes': [models.Index(fields=['artifact', 'revision'], name='idx_artifactversion_hist')],
                'constraints': [models.UniqueConstraint(fields=('artifact', 'revision'), name='uq_artifact_version_revision')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
