# Generated by Django 6.1 on 2026-09-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0078_migrate_legacy_versions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlossaryTermVersion',
        ),
    ]
