# Generated by Django 6.1.1 on 2026-09-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0079_drop_glossary_term_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text="Provenance of a duplicated artifact. Replaces the retired 'copy-of' TraceLink type: a copy has exactly one origin, so a 1:1 field states the invariant that an N:M link table could not. SET_NULL — deleting the original must not delete its copies, which are independent artifacts.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='persistence.artifact'),
        ),
        migrations.AddField(
            model_name='tracelink',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text='Q1.6: why this link exists. A link type alone does not say why *these two* artifacts are connected; without it a reviewer has to reconstruct the intent from the two titles.'),
        ),
        migrations.AddField(
            model_name='tracelink',
            name='suspect_flagged_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Set by the suspect-propagation engine (application.trace_link_service.TraceLinkService.propagate_suspect_status) when this link caused the other endpoint to be flagged suspect. NULL means this link has not triggered a flag since the last review.', null=True),
        ),
        migrations.AddField(
            model_name='tracelink',
            name='suspect_source_change',
            field=models.UUIDField(blank=True, help_text='audit.AuditEntry.id of the change that triggered the flag above. Deliberately a plain UUID rather than a ForeignKey: audit_entry is append-only and slated for monthly RANGE partitioning (audit/migrations/0001_initial.py), which a real FK would permanently block because Postgres requires the partition key in the referenced primary key. No cascade semantics are needed — an audit entry is never deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='decomposition_link_type',
            field=models.CharField(default='decomposes', help_text="Default link type used when decomposing requirements. NOTE: RequirementService.decompose hardcodes 'decomposes' and does not read this field (UMSETZUNGSPLAN_SYSENG_2.0 section 1.4); the default was 'parent-child', a link type that no longer exists.", max_length=50),
        ),
    ]
