# Generated by Django 6.1.1 on 2026-09-09 17:04
#
# Deploy note — `suspect_flagged_at`'s index is built CONCURRENTLY.
#
# `pl_tracelink` is the highest-cardinality table in the system. A plain
# `db_index=True` on the AddField issues a blocking `CREATE INDEX`, which takes
# a lock that prevents writes to the whole table for its duration — a real
# deploy-window concern at production scale, and one that used to be
# undocumented here. The column is therefore added without an index, and the
# index is created afterwards via `AddIndexConcurrently` inside a
# `SeparateDatabaseAndState`: the state half keeps `db_index=True` so migration
# state still matches `persistence.models.TraceLink` (`makemigrations --check`
# stays clean), while the database half builds the index without the lock.
#
# `atomic = False` is mandatory for that: PostgreSQL refuses
# `CREATE INDEX CONCURRENTLY` inside a transaction block, and Django only runs
# the operation outside one when the migration says so. The trade-off is that a
# failure part-way through leaves this migration partially applied — acceptable
# here because every operation is an additive `AddField`/`AlterField` and
# re-running after a fix is safe. The index name is pinned to the value Django
# generated for the original `db_index=True` version so a database migrated
# before this change and one migrated after it carry the identical index.

import django.db.models.deletion
from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models

#: Django's own auto-generated name for the former `db_index=True` index.
SUSPECT_FLAGGED_AT_INDEX = 'pl_tracelink_suspect_flagged_at_a2684144'

SUSPECT_FLAGGED_AT_HELP_TEXT = (
    'Set by the suspect-propagation engine '
    '(application.trace_link_service.TraceLinkService.propagate_suspect_status) '
    'when this link caused the other endpoint to be flagged suspect. NULL means '
    'this link has not triggered a flag since the last review.'
)


class Migration(migrations.Migration):

    # See the module comment: required by AddIndexConcurrently.
    atomic = False

    dependencies = [
        ('persistence', '0079_drop_glossary_term_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='copied_from',
            field=models.ForeignKey(blank=True, help_text="Provenance of a duplicated artifact. Replaces the retired copy-of TraceLink type: a copy has exactly one origin, so a 1:1 field states the invariant that an N:M link table could not. SET_NULL — deleting the original must not delete its copies, which are independent artifacts.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='persistence.artifact'),
        ),
        migrations.AddField(
            model_name='tracelink',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text='Q1.6: why this link exists. A link type alone does not say why *these two* artifacts are connected; without it a reviewer has to reconstruct the intent from the two titles.'),
        ),
        # Column only — no index. The index follows below, concurrently.
        migrations.AddField(
            model_name='tracelink',
            name='suspect_flagged_at',
            field=models.DateTimeField(blank=True, help_text=SUSPECT_FLAGGED_AT_HELP_TEXT, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                AddIndexConcurrently(
                    model_name='tracelink',
                    index=models.Index(
                        fields=['suspect_flagged_at'],
                        name=SUSPECT_FLAGGED_AT_INDEX,
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='tracelink',
                    name='suspect_flagged_at',
                    field=models.DateTimeField(blank=True, db_index=True, help_text=SUSPECT_FLAGGED_AT_HELP_TEXT, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='tracelink',
            name='suspect_source_change',
            field=models.UUIDField(blank=True, help_text='audit.AuditEntry.id of the change that triggered the flag above. Deliberately a plain UUID rather than a ForeignKey: audit_entry is append-only and slated for monthly RANGE partitioning (audit/migrations/0001_initial.py), which a real FK would permanently block because Postgres requires the partition key in the referenced primary key. No cascade semantics are needed — an audit entry is never deleted.', null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='decomposition_link_type',
            field=models.CharField(default='decomposes', help_text="Default link type used when decomposing requirements. NOTE: RequirementService.decompose hardcodes `decomposes` and does not read this field (UMSETZUNGSPLAN_SYSENG_2.0 section 1.4); the default was the now-retired parent/child link key.", max_length=50),
        ),
    ]
