# Generated by Django 6.1.1 on 2026-09-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0080_retire_legacy_field_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
