# Generated by Django 6.1.1 on 2026-09-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0081_adr_description_blank'),
        ('persistence', '0081_migrate_trace_link_types'),
    ]

    operations = [
    ]
