# Generated by Django 6.1.1 on 2026-09-11 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0013_apikey_agent_identity'),
        ('persistence', '0082_merge_traceability_and_attribute_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracelink',
            name='proposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracelink',
            name='proposed_by',
            field=models.ForeignKey(blank=True, help_text='API key of the AI agent that proposed this link; NULL once a human confirmed it or when a human created it directly.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_trace_links', to='auth_tenancy.apikey'),
        ),
    ]
