# Generated by Django 6.1.1 on 2026-09-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0082_merge_traceability_and_attribute_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='transcript_summary',
            field=models.TextField(blank=True, default='', help_text='L2.4: LLM-compressed digest of the turns that fell out of the sliding transcript window (InterviewService.TRANSCRIPT_WINDOW_TURNS). Prepended to the chat prompt instead of the full history, so prompt size stops growing with session length. Empty, never NULL: every read path concatenates it.'),
        ),
    ]
