# Generated by Django 6.1.1 on 2026-09-11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0083_interview_transcript_summary'),
        ('persistence', '0083_tracelink_proposed_by'),
    ]

    operations = [
    ]
