"""
COMP-PL-001 EntitySchemaManager — Actor entity + Artifact system fields.

Attribut v3 WS2 (#936, spec sections 3 and 4):

* ``Actor`` (``pl_actor``) carries internal users and external dummies in one
  table; ``Artifact.owner``/``Artifact.reporter`` reference it.
* ``Artifact.priority`` is a plain ``CharField`` without model choices — the
  scale is defined per attribute definition (type=enum), not frozen in the DB.

All three are added to ``pl_artifact``, so every one of the 11 item types
inherits them without a per-type migration. Purely additive: no existing column
is altered or dropped (the legacy ``Risk.owner`` free-text column stays and is
folded into the Actor model by AWMS/WS7). RLS for ``pl_actor`` ships in
``0086_actor_rls_policy`` (the coverage guard in persistence/tests/test_rls_coverage.py
requires its own migration).
"""
# Generated by Django 6.1.1 on 2026-09-13 11:29

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0084_merge_interview_and_workflow_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='priority',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Spec section 3: priority value. Deliberately no model-level choices — the scale is defined per attribute definition (type=enum, default low/medium/high/critical).', max_length=64),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('kind', models.CharField(choices=[('user', 'User'), ('external', 'External')], max_length=16)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
                ('user', models.ForeignKey(blank=True, help_text="Spec section 4: set for kind='user', NULL for externals.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pl_actor',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='artifact',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Spec section 3: attributed owner (internal user or external dummy).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.actor'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reporter',
            field=models.ForeignKey(blank=True, help_text='Spec section 3: person/team that reported the artifact.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.actor'),
        ),
        migrations.AddIndex(
            model_name='actor',
            index=models.Index(fields=['tenant', 'is_active'], name='idx_actor_tnt_active'),
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('tenant', 'user'), name='uq_actor_tenant_user'),
        ),
        migrations.AddConstraint(
            model_name='actor',
            constraint=models.UniqueConstraint(models.F('tenant'), django.db.models.functions.text.Lower('display_name'), condition=models.Q(('kind', 'external')), name='uq_actor_tenant_external_name'),
        ),
    ]
