# Generated by Django 6.1.1 on 2026-09-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0086_actor_rls_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='architectureelement',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholderneed',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='uid',
            field=models.CharField(blank=True, help_text="External import key (ReqIF); never auto-generated - the Artifact UUID 'id' is the identity.", max_length=64, null=True),
        ),
    ]
