# Generated by Django 6.1.1 on 2026-09-13 18:23

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0087_alter_adr_uid_alter_architectureelement_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeCatalogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=64)),
                ('definition', models.JSONField()),
                ('category', models.CharField(blank=True, max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('label', models.JSONField(default=dict)),
                ('help_text', models.JSONField(default=dict)),
                ('origin', models.CharField(blank=True, max_length=64)),
                ('deprecated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_attribute_catalog_entry',
                'indexes': [models.Index(fields=['tenant', 'category'], name='idx_attr_catalog_tnt_cat')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uq_attribute_catalog_tenant_name')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
