# Generated by Django 6.1.1 on 2026-09-13 20:38

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0089_attribute_catalog_rls_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeMigrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('plan_id', models.CharField(max_length=128)),
                ('plan_hash', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('dry_run', 'Dry run'), ('apply', 'Apply')], max_length=16)),
                ('status', models.CharField(choices=[('planned', 'Planned (dry run)'), ('applied', 'Applied'), ('partial', 'Partially applied'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], default='planned', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor_type', models.CharField(default='user', max_length=16)),
                ('actor_label', models.CharField(blank=True, default='', max_length=255)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('report_json', models.JSONField(blank=True, default=dict)),
                ('snapshot_reference', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_attribute_migration_run',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AttributeMigrationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('artifact_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('model_fields', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='persistence.attributemigrationrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_attribute_migration_snapshot',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='attributemigrationrun',
            index=models.Index(fields=['tenant', 'plan_id'], name='idx_amr_tnt_plan'),
        ),
        migrations.AddIndex(
            model_name='attributemigrationrun',
            index=models.Index(fields=['tenant', 'started_at'], name='idx_amr_tnt_started'),
        ),
        migrations.AddIndex(
            model_name='attributemigrationsnapshot',
            index=models.Index(fields=['tenant', 'run'], name='idx_ams_tnt_run'),
        ),
        migrations.AddConstraint(
            model_name='attributemigrationsnapshot',
            constraint=models.UniqueConstraint(fields=('run', 'artifact_id'), name='uq_attr_mig_snapshot_run_artifact'),
        ),
    ]
