# Generated by Django 6.1.1 on 2026-09-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0093_normalize_testcase_artifact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='reqif_alt_ids',
            field=models.JSONField(blank=True, default=list, help_text='ReqIF ALT-ID aliases (list of strings) of this external artifact, for tools that track more than one identifier.', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reqif_identifier',
            field=models.CharField(blank=True, help_text="Incoming ReqIF SPEC-OBJECT IDENTIFIER. The exporter emits it verbatim when set, so a re-export back to a foreign tool keeps that tool's identity; when NULL the exporter falls back to '_<Artifact.id>'.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reqif_imported_at',
            field=models.DateTimeField(blank=True, help_text='When this artifact was last created/updated by a ReqIF import.', null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reqif_source_project',
            field=models.CharField(blank=True, default='', help_text='ReqIF source project/specification identifier.', max_length=255),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reqif_source_tool',
            field=models.CharField(blank=True, default='', help_text="ReqIF source tool, e.g. 'DOORS', 'Polarion', 'codebeamer'.", max_length=64),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reqif_uid',
            field=models.CharField(blank=True, help_text='External UID assigned by the source tool (the ReqIF ATTR-UID attribute). Deliberately separate from the local, auto-generated ``uid``.', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(condition=models.Q(('reqif_identifier__isnull', False), models.Q(('reqif_identifier', ''), _negated=True)), fields=('workspace', 'reqif_identifier'), name='uq_artifact_reqif_identifier'),
        ),
        migrations.AddConstraint(
            model_name='artifact',
            constraint=models.UniqueConstraint(condition=models.Q(('reqif_uid__isnull', False), models.Q(('reqif_uid', ''), _negated=True)), fields=('workspace', 'reqif_uid'), name='uq_artifact_reqif_uid'),
        ),
    ]
