# Generated by Django 6.1.1 on 2026-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0095_uidsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='architectureelement',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='stakeholderneed',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='testrun',
            name='uid',
            field=models.CharField(blank=True, help_text="Local readable identifier, auto-generated per (workspace, item_type) as '<PREFIX>-NNN' (issue #932). External ReqIF identity lives on Artifact.reqif_uid/reqif_identifier, not here.", max_length=64, null=True),
        ),
    ]
