# Generated by Django 6.1.1 on 2026-09-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0097_uid_sequence_rls_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='rationale',
            field=models.TextField(blank=True, default='', help_text="#871/#583: justification for the requirement (IEEE 29148 §5.2.6). Previously squeezed into 'description'."),
        ),
        migrations.AddField(
            model_name='requirement',
            name='source',
            field=models.CharField(blank=True, default='', help_text='#871: origin of the requirement (stakeholder, document, decision). A named owner is the Artifact-level `owner` system field.', max_length=255),
        ),
    ]
