"""
AWMS definition snapshots (issue #1082) + the partially-rolled-back run status.

Two changes, both about the data model not lying:

* ``AttributeMigrationSnapshot`` only ever recorded artifact **value** changes,
  so a plan step like ``define_attribute`` left no before-image at all. Its
  rollback then answered ``{"status": "rolled_back", "restored": 0}`` while the
  definitions it had written into ``ad_global_definition`` survived. The new
  ``AttributeDefinitionSnapshot`` carries the before-image of a definition
  target (``ad_global_definition`` or ``ad_workspace_definition``) and an
  ``existed`` flag, so rollback can *delete* a target the run created instead
  of leaving a row that claims an empty attribute set.
* ``AttributeMigrationRun.status`` grows ``partially_rolled_back``. With the
  new snapshot table it is only reachable for a run applied before this
  migration (no definition before-image exists) or a target row deleted
  meanwhile — and it exists so a rollback can never report success while
  something it changed stayed changed. The column widens from 16 to 32 because
  the new value is 21 characters.

RLS: the new table is a ``TenantScopedModel``, so it ships the same
ENABLE + FORCE ROW LEVEL SECURITY + ``tenant_id`` policy as every other
tenant-scoped table (``persistence/tests/test_rls_coverage.py`` enforces one
per new model). It is folded into this migration rather than shipped as a
separate one so the app keeps a single migration leaf.

Generated by Django 6.1.1; the ``RunSQL`` block and the docstring are
hand-written (same shape as ``persistence/0091_attribute_migration_rls_policy.py``).

Requirements: REQ-L2-PL-010 (RLS on all tenant-scoped tables), ADR-PL-03.
"""
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models

_TABLE = "pl_attribute_definition_snapshot"
_POLICY = f"{_TABLE}_tenant_isolation"


def _rls_sql() -> str:
    return (
        f"ALTER TABLE {_TABLE} ENABLE ROW LEVEL SECURITY;\n"
        f"ALTER TABLE {_TABLE} FORCE ROW LEVEL SECURITY;\n"
        f"CREATE POLICY {_POLICY} ON {_TABLE}\n"
        "    USING (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid)\n"
        "    WITH CHECK (tenant_id = NULLIF(current_setting('app.current_tenant', true), '')::uuid);"
    )


def _rls_reverse_sql() -> str:
    return (
        f"DROP POLICY IF EXISTS {_POLICY} ON {_TABLE};\n"
        f"ALTER TABLE {_TABLE} NO FORCE ROW LEVEL SECURITY;\n"
        f"ALTER TABLE {_TABLE} DISABLE ROW LEVEL SECURITY;"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0100_workspace_goals_enabled_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributemigrationrun',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned (dry run)'), ('applied', 'Applied'), ('partial', 'Partially applied'), ('failed', 'Failed'), ('rolled_back', 'Rolled back'), ('partially_rolled_back', 'Partially rolled back')], default='planned', max_length=32),
        ),
        migrations.CreateModel(
            name='AttributeDefinitionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('target_key', models.CharField(max_length=255)),
                ('target_kind', models.CharField(choices=[('global', 'Global (tenant preset)'), ('workspace', 'Workspace')], max_length=16)),
                ('item_type', models.CharField(max_length=128)),
                ('preset', models.CharField(blank=True, default='', max_length=32)),
                ('workspace_id', models.UUIDField(blank=True, null=True)),
                ('existed', models.BooleanField(default=True)),
                ('definition_json', models.JSONField(blank=True, null=True)),
                ('is_customized', models.BooleanField(blank=True, null=True)),
                ('previous_version', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definition_snapshots', to='persistence.attributemigrationrun')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'pl_attribute_definition_snapshot',
                'indexes': [models.Index(fields=['tenant', 'run'], name='idx_adst_tnt_run')],
                'constraints': [models.UniqueConstraint(fields=('run', 'target_key'), name='uq_attr_def_snapshot_run_target')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunSQL(sql=_rls_sql(), reverse_sql=_rls_reverse_sql()),
    ]
