# Generated by Django 6.1.1 on 2026-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0102_adr_deciders_issue_assignee_artifact_stakeholder'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='goal',
            constraint=models.UniqueConstraint(fields=('lineage_id', 'sequence_number'), name='uq_goal_lineage_sequence'),
        ),
    ]
