# Generated by Django 6.1.1 on 2026-10-08 00:08

import uuid

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_tenancy', '0020_user_display_preference_rls'),
        ('persistence', '0106_alter_llmsettings_provider_azure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('kind', models.CharField(choices=[('artifact_create', 'Artifact create'), ('trace_link', 'Trace link'), ('interview_grounding', 'Interview grounding'), ('context_edge', 'Context edge')], max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='open', max_length=16)),
                ('producer', models.CharField(blank=True, default='', help_text="Service/agent label of the trusted producer (e.g. 'traceability.suggest_links'). Server-set from producer code, never from a request body.", max_length=255)),
                ('proposed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Server-set creation time of the proposal receipt.')),
                ('decided_at', models.DateTimeField(blank=True, help_text='Server-set decision time; NULL while the suggestion is open.', null=True)),
                ('target_item_type', models.CharField(blank=True, default='', help_text="Kind-specific target label (e.g. 'TraceLink'): the entity the adapter acts on. Empty for a free-standing proposal.", max_length=64)),
                ('target_item_id', models.UUIDField(blank=True, help_text='UUID of the delegated target (e.g. the M2 proposal TraceLink id); NULL when the adapter has nothing to reference yet.', null=True)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='UNTRUSTED producer payload (candidate ids, scores, rationale, ranking). Never blind-materialized; validated through the delegated domain path only.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, help_text='Human principal who accepted/rejected; NULL while the suggestion is still open.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, help_text='API key of the producing agent (M2 semantics, like TraceLink.proposed_by); server-set from ctx.api_key_id.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_suggestions', to='auth_tenancy.apikey')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='persistence.workspace')),
            ],
            options={
                'db_table': 'pl_suggestion',
                'indexes': [models.Index(fields=['workspace', 'status'], name='idx_suggestion_ws_status')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
