"""Add structured IcdParameter model and mechanical/electrical interface types.

REQ-L2-ICD-002 (Design-by-Contract): extends the free-text pre/post/invariant
JSON lists with a structured, version-specific parameter model that carries
units, numeric value ranges (min/max), nominal values and tolerances.

Also widens IcdVersion.interface_type choices with ``mechanical`` and
``electrical`` (used by seed_toothbrush.py but previously absent from the
IcdType choices — Django choices validate only at the form/serializer level).

Backward-compatible: purely additive. AlterField only extends the choice set of
an existing CharField (no data change); CreateModel adds a new, unreferenced
table. The reverse migration drops the new table and restores the prior
choice set, so up -> down -> up is deterministic.

Generated by Django 4.2.30, then documented and formatted by hand.
"""
from __future__ import annotations

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0038_workspace_default_link_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icd', '0004_add_icd_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdversion',
            name='interface_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('provides', 'Provides'),
                    ('requires', 'Requires'),
                    ('event-in', 'Event In'),
                    ('event-out', 'Event Out'),
                    ('data', 'Data'),
                    ('control', 'Control'),
                    ('mechanical', 'Mechanical'),
                    ('electrical', 'Electrical'),
                ],
                default='',
                help_text=(
                    'Interface type classification: provides, requires, '
                    'event-in, event-out, data, control.'
                ),
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name='IcdParameter',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=200)),
                (
                    'description',
                    models.CharField(blank=True, default='', max_length=2000),
                ),
                (
                    'unit',
                    models.CharField(blank=True, default='', max_length=50),
                ),
                (
                    'data_type',
                    models.CharField(
                        choices=[
                            ('float', 'Float'),
                            ('int', 'Integer'),
                            ('string', 'String'),
                            ('boolean', 'Boolean'),
                            ('enum', 'Enum'),
                            ('other', 'Other'),
                        ],
                        default='other',
                        max_length=20,
                    ),
                ),
                (
                    'direction',
                    models.CharField(
                        choices=[
                            ('input', 'Input'),
                            ('output', 'Output'),
                            ('bidirectional', 'Bidirectional'),
                        ],
                        default='input',
                        max_length=15,
                    ),
                ),
                (
                    'min_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    'max_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    'nominal_value',
                    models.CharField(blank=True, default='', max_length=200),
                ),
                (
                    'tolerance',
                    models.CharField(blank=True, default='', max_length=100),
                ),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'icd_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='parameters',
                        to='icd.icdversion',
                    ),
                ),
                (
                    'modified_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'tenant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='%(class)s_set',
                        to='persistence.tenant',
                    ),
                ),
            ],
            options={
                'db_table': 'icd_parameter',
                'ordering': ['ordering', 'name'],
                'indexes': [
                    models.Index(
                        fields=['icd_version', 'ordering'],
                        name='idx_icd_param_version_order',
                    ),
                ],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
