# Generated by Django 6.1 on 2026-09-05 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd', '0008_align_icdversion_embedding_dimensions'),
        ('persistence', '0072_glossary_changerequest_artifact_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd',
            name='artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icd', to='persistence.artifact'),
        ),
    ]
