# Generated by Django 6.1 on 2026-09-06 08:49

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icd', '0009_icd_artifact_fk'),
        ('persistence', '0079_drop_glossary_term_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='icd',
            name='current_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='icd',
            name='direction',
            field=models.CharField(choices=[('unidirectional', 'Unidirectional'), ('bidirectional', 'Bidirectional')], default='unidirectional', max_length=32),
        ),
        migrations.AddField(
            model_name='icd',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, help_text='REQ-L2-VS-004: Semantic embedding for cosine similarity search, sized by persistence.embedding_dimensions.EMBEDDING_VECTOR_DIMENSIONS (#794). Unlike IcdVersion.embedding this row is mutable, so it is re-generated on every contract change. Best-effort: NULL when no embedding provider is configured.', null=True),
        ),
        migrations.AddField(
            model_name='icd',
            name='interface_type',
            field=models.CharField(blank=True, choices=[('provides', 'Provides'), ('requires', 'Requires'), ('event-in', 'Event In'), ('event-out', 'Event Out'), ('data', 'Data'), ('control', 'Control'), ('mechanical', 'Mechanical'), ('electrical', 'Electrical')], default='', help_text='Interface type classification: provides, requires, event-in, event-out, data, control.', max_length=32),
        ),
        migrations.AddField(
            model_name='icd',
            name='invariants',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd',
            name='postconditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd',
            name='preconditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='icd',
            name='semantic_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='icdparameter',
            name='icd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='icd.icd'),
        ),
        migrations.AddIndex(
            model_name='icd',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='icd_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
