# Generated by Django 6.0.6 on 2026-06-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_alter_diagram_options_alter_diagramversion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='diagram_type',
            field=models.CharField(choices=[('block', 'Block Diagram'), ('flow', 'Flow Diagram'), ('context', 'Context Diagram'), ('canvas', 'Canvas Drawing'), ('mermaid', 'Mermaid Diagram')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='diagramversion',
            name='payload_format',
            field=models.CharField(choices=[('mermaid', 'Mermaid'), ('plantuml', 'PlantUML'), ('json', 'Structured JSON'), ('canvas_stroke', 'Canvas Stroke Data (JSON)')], max_length=16),
        ),
    ]
