# Generated by Django 4.2.30 on 2026-08-07 17:42
#
# Codeberg #353 Task 3 / #392: adds a nullable, lazily-populated 1:1
# shadow-Artifact side-channel FK to Diagram. Additive column only — no
# backfill, no data migration (existing Diagram rows keep artifact=NULL
# until diagram.traceability_connector._resolve_artifact_id first needs
# one). Lives under diagram/migrations/ because Diagram is defined in
# diagram/models.py, even though the field references persistence.Artifact.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0058_workspace_description'),
        ('diagram', '0006_add_node_graph_payload_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='artifact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagram', to='persistence.artifact'),
        ),
    ]
