# Generated by Django 6.1 on 2026-09-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0008_diagram_rls_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagram',
            name='canvas_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='diagram',
            name='current_revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagram',
            name='payload',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='diagram',
            name='payload_format',
            field=models.CharField(blank=True, choices=[('mermaid', 'Mermaid'), ('plantuml', 'PlantUML'), ('json', 'Structured JSON'), ('canvas_stroke', 'Canvas Stroke Data (JSON)'), ('node_graph', 'Node Graph (JSON)')], default='', max_length=16),
        ),
    ]
