# Generated by Django 5.2.17 on 2026-08-25 12:36

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models

from admin_ops.theme_seed_data import (
    BAUHAUS_DARK,
    BAUHAUS_LIGHT,
    DEFAULT_DARK,
    DEFAULT_LIGHT,
    NORDIC_DARK,
    NORDIC_LIGHT,
    SEPIA_DARK,
    SEPIA_LIGHT,
)


_SEED_TOKENS = {
    "default": ("Default", DEFAULT_DARK, DEFAULT_LIGHT),
    "bauhaus": ("Bauhaus", BAUHAUS_DARK, BAUHAUS_LIGHT),
    "nordic": ("Nordic", NORDIC_DARK, NORDIC_LIGHT),
    "sepia": ("Sepia", SEPIA_DARK, SEPIA_LIGHT),
}


def seed_system_palettes(apps, schema_editor):
    """Create one row of every stock palette for every existing tenant."""
    ThemePalette = apps.get_model("admin_ops", "ThemePalette")
    Tenant = apps.get_model("persistence", "Tenant")

    for tenant in Tenant.objects.all():
        for key, (label, dark, light) in _SEED_TOKENS.items():
            ThemePalette.objects.create(
                tenant=tenant,
                key=key,
                label=label,
                is_system=True,
                dark_tokens=dark,
                light_tokens=light,
                token_keys_version="v1",
            )


def unseed_system_palettes(apps, schema_editor):
    ThemePalette = apps.get_model("admin_ops", "ThemePalette")
    ThemePalette.unscoped.filter(is_system=True).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0003_banner_rls'),
        ('persistence', '0066_interview_multi_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePalette',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('key', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=128)),
                ('is_system', models.BooleanField(default=False)),
                ('dark_tokens', models.JSONField()),
                ('light_tokens', models.JSONField()),
                ('token_keys_version', models.CharField(default='v1', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'admin_ops_theme_palette',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'key'), name='uq_theme_palette_tenant_key')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(seed_system_palettes, unseed_system_palettes),
    ]
