# Generated by Django 6.0.6 on 2026-06-24 19:48

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persistence', '0003_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakerState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('target_subsystem', models.CharField(help_text='Identifier of the external target this breaker protects.', max_length=32)),
                ('state', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('half_open', 'Half-Open')], default='closed', help_text='Current circuit state (REQ-L3-RO-003-01).', max_length=16)),
                ('failure_count', models.IntegerField(default=0, help_text='Consecutive failures accumulated in the current window.')),
                ('last_failure_at', models.DateTimeField(blank=True, help_text='UTC timestamp of the most recent recorded failure.', null=True)),
                ('opened_at', models.DateTimeField(blank=True, help_text='When the breaker last transitioned to Open; basis for the recovery timeout that allows the Half-Open probe (REQ-L3-RO-003-04).', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.user')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='persistence.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'verbose_name': 'Circuit Breaker State',
                'verbose_name_plural': 'Circuit Breaker States',
                'indexes': [models.Index(fields=['tenant', 'target_subsystem'], name='resilience__tenant__ed0225_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'target_subsystem'), name='uniq_circuit_per_tenant_target')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
