# Generated by Django 4.2.30 on 2026-06-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_adr_risk_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domaineventoutbox',
            name='event_type',
            field=models.CharField(choices=[('RequirementCreated', 'Requirement Created'), ('RequirementUpdated', 'Requirement Updated'), ('RequirementDeleted', 'Requirement Deleted'), ('ArchitectureElementCreated', 'Architecture Element Created'), ('ArchitectureElementUpdated', 'Architecture Element Updated'), ('ArchitectureElementDeleted', 'Architecture Element Deleted'), ('TestCaseCreated', 'Test Case Created'), ('TestCaseUpdated', 'Test Case Updated'), ('TestCaseDeleted', 'Test Case Deleted'), ('BaselineCreated', 'Baseline Created'), ('WorkflowTransitioned', 'Workflow Transitioned'), ('AdrCreated', 'Adr Created'), ('AdrUpdated', 'Adr Updated'), ('AdrDeleted', 'Adr Deleted'), ('RiskCreated', 'Risk Created'), ('RiskUpdated', 'Risk Updated'), ('RiskDeleted', 'Risk Deleted'), ('IssueCreated', 'Issue Created'), ('IssueUpdated', 'Issue Updated'), ('IssueDeleted', 'Issue Deleted')], max_length=64),
        ),
    ]
