# Generated by Django 4.2.30 on 2026-07-30 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0051_user_username_ci_unique'),
        ('application', '0011_add_change_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='domaineventoutbox',
            name='event_type',
            field=models.CharField(choices=[('RequirementCreated', 'Requirement Created'), ('RequirementUpdated', 'Requirement Updated'), ('RequirementDeleted', 'Requirement Deleted'), ('ArchitectureElementCreated', 'Architecture Element Created'), ('ArchitectureElementUpdated', 'Architecture Element Updated'), ('ArchitectureElementDeleted', 'Architecture Element Deleted'), ('TestCaseCreated', 'Test Case Created'), ('TestCaseUpdated', 'Test Case Updated'), ('TestCaseDeleted', 'Test Case Deleted'), ('BaselineCreated', 'Baseline Created'), ('WorkflowTransitioned', 'Workflow Transitioned'), ('AdrCreated', 'Adr Created'), ('AdrUpdated', 'Adr Updated'), ('AdrDeleted', 'Adr Deleted'), ('RiskCreated', 'Risk Created'), ('RiskUpdated', 'Risk Updated'), ('RiskDeleted', 'Risk Deleted'), ('IssueCreated', 'Issue Created'), ('IssueUpdated', 'Issue Updated'), ('IssueDeleted', 'Issue Deleted'), ('ChangeRequestCreated', 'Change Request Created'), ('ChangeRequestUpdated', 'Change Request Updated'), ('ChangeRequestDeleted', 'Change Request Deleted')], max_length=64),
        ),
        migrations.CreateModel(
            name='MainGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('ai', 'AI'), ('manual', 'Manual')], max_length=20)),
                ('generated_from_goal_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(default='Entwurf', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_goal', to='persistence.artifact')),
            ],
            options={
                'db_table': 'as_main_goal',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['workspace_id', 'status'], name='as_main_goa_workspa_5fb424_idx'), models.Index(fields=['workspace_id', 'sequence_number'], name='as_main_goa_workspa_548196_idx')],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField(db_index=True)),
                ('workspace_id', models.UUIDField(db_index=True)),
                ('lineage_id', models.UUIDField(db_index=True)),
                ('sequence_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Entwurf', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='persistence.artifact')),
            ],
            options={
                'db_table': 'as_goal',
                'ordering': ['lineage_id', 'sequence_number'],
                'indexes': [models.Index(fields=['workspace_id', 'lineage_id'], name='as_goal_workspa_9319d2_idx'), models.Index(fields=['workspace_id', 'status'], name='as_goal_workspa_065dd3_idx')],
            },
        ),
    ]
