# Generated by Django 4.2.30 on 2026-08-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_change_request_affected_items_and_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='adr',
            name='decision',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
