# Generated by Django 6.1 on 2026-09-04 19:39
#
# Datenmodell-Konsolidierung Task 12: drops the denormalized `status` mirror
# columns on Adr/Risk/Issue/ChangeRequest/Goal/MainGoal.
#
# Explicit extra dependency on workflow.0005: that RunPython data migration
# reads/writes `.status` on a historical apps.get_model() snapshot of
# Adr/Risk/Issue/ChangeRequest. Without this edge, Django's migration-plan
# topological sort could place this migration before it on a fresh `migrate`
# from zero -- see persistence/migrations/0070_drop_status_mirror_columns.py
# for the confirmed failure this mirrors (workflow.0014 crashed the same way
# for TestCase before that migration gained the equivalent edges).
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_main_goal_sequence_unique'),
        ('workflow', '0005_backfill_entity_item_states'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='adr',
            name='idx_adr_ws_status',
        ),
        migrations.RemoveIndex(
            model_name='changerequest',
            name='idx_cr_ws_status',
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='as_goal_workspa_065dd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='idx_issue_ws_status',
        ),
        migrations.RemoveIndex(
            model_name='maingoal',
            name='as_main_goa_workspa_5fb424_idx',
        ),
        migrations.RemoveIndex(
            model_name='risk',
            name='idx_risk_ws_status',
        ),
        migrations.RemoveField(
            model_name='adr',
            name='status',
        ),
        migrations.RemoveField(
            model_name='changerequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='status',
        ),
        migrations.RemoveField(
            model_name='maingoal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='status',
        ),
    ]
