# Generated by Django 6.1 on 2026-09-05 05:52

from django.db import migrations, models


def _backfill_modified_at(apps_registry, schema_editor):
    """Seed modified_at from updated_at so no row starts NULL."""
    for model_name in ("Adr", "Risk", "Goal", "MainGoal", "Issue", "ChangeRequest"):
        model = apps_registry.get_model("application", model_name)
        model.objects.filter(modified_at__isnull=True).update(
            modified_at=models.F("updated_at")
        )


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_drop_status_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adr',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=255),
        ),
        migrations.RenameField(
            model_name='adr',
            old_name='created_by',
            new_name='created_by_name',
        ),
        migrations.AlterField(
            model_name='changerequest',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=255),
        ),
        migrations.RenameField(
            model_name='changerequest',
            old_name='created_by',
            new_name='created_by_name',
        ),
        migrations.AlterField(
            model_name='goal',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=255),
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='created_by',
            new_name='created_by_name',
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=255),
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='created_by',
            new_name='created_by_name',
        ),
        migrations.AlterField(
            model_name='maingoal',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=255),
        ),
        migrations.RenameField(
            model_name='maingoal',
            old_name='created_by',
            new_name='created_by_name',
        ),
        migrations.AlterField(
            model_name='risk',
            name='created_by',
            field=models.CharField(blank=True, db_column='created_by', max_length=255),
        ),
        migrations.RenameField(
            model_name='risk',
            old_name='created_by',
            new_name='created_by_name',
        ),
        migrations.AddField(
            model_name='adr',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adr',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='adr',
            name='modified_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='modified_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='modified_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='modified_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='maingoal',
            name='modified_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='created_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='modified_by_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(_backfill_modified_at, migrations.RunPython.noop),
    ]
