# Generated by Django 6.1.1 on 2026-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0028_import_idempotency_record'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='importidempotencyrecord',
            name='idx_import_idem_expires',
        ),
        migrations.AlterField(
            model_name='importidempotencyrecord',
            name='expires_at',
            field=models.DateTimeField(),
        ),
    ]
