# Generated by Django 4.2.30 on 2026-06-25 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_alter_architectureelement_options_and_more'),
        ('presets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspacepresetconfig',
            options={},
        ),
        migrations.AlterModelManagers(
            name='workspacepresetconfig',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='workspacepresetconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
    ]
