"""
Django admin registration for the icd app (COMP-ICD-001/002, REQ-L1-028).

Registers:

* :class:`Icd` — mutable logical identity of an Interface Control Document
* :class:`IcdVersion` — append-only immutable contract revision

Read-only:
    ``IcdVersion`` is immutable (mirroring the DB-level immutability triggers);
    the admin is locked down to read-only to match.

Tenant isolation:
    Both models inherit ``TenantScopedModel`` (they re-declare ``objects`` and
    ``unscoped`` explicitly in icd.models). ``get_queryset`` uses
    ``unscoped()`` to bypass the tenant filter.
"""
from __future__ import annotations

from django.contrib import admin

from .models import Icd, IcdVersion


@admin.register(Icd)
class IcdAdmin(admin.ModelAdmin):
    """Admin view for the Icd header (REQ-L2-ICD-001/002)."""

    list_display = (
        "name",
        "source_element_id",
        "target_element_id",
        "workspace_id",
        "tenant",
        "current_version",
    )
    list_filter = ("tenant", "workspace_id")
    search_fields = ("name", "source_element_id", "target_element_id")
    ordering = ("-created_at",)
    readonly_fields = ("created_at", "created_by", "modified_at", "modified_by", "version")
    # ``embedding`` (Task 28c-1) is a derived pgvector column, not user data:
    # rendering 384 floats in a form only invites a round-trip that corrupts
    # them on save. Regenerated by the write path / backfill_embeddings.
    exclude = ("embedding",)

    def get_queryset(self, request):
        # CRITICAL: bypass the tenant-isolating default manager.
        return Icd.unscoped.all()


@admin.register(IcdVersion)
class IcdVersionAdmin(admin.ModelAdmin):
    """Admin view for the immutable IcdVersion (REQ-L2-ICD-001/002).

    Read-only: each IcdVersion is an immutable contract revision. Updates
    append a new version rather than modifying an existing row; the DB
    trigger in migration 0001_initial enforces immutability at the database.
    """

    list_display = (
        "icd",
        "version_number",
        "direction",
        "interface_type",
        "tenant",
        "created_at",
    )
    list_filter = ("tenant", "direction", "interface_type")
    search_fields = ("icd__name", "interface_type", "semantic_description")
    ordering = ("icd", "-version_number")
    readonly_fields = (
        "icd",
        "version_number",
        "direction",
        "interface_type",
        "semantic_description",
        "preconditions",
        "postconditions",
        "invariants",
        "created_at",
        "created_by",
        "modified_at",
        "modified_by",
        "version",
        "tenant",
    )

    def get_queryset(self, request):
        return IcdVersion.unscoped.all()

    def has_add_permission(self, request):
        return False  # read-only

    def has_change_permission(self, request, obj=None):
        return False  # read-only

    def has_delete_permission(self, request, obj=None):
        return False  # read-only
