"""
Django admin registration for the icd app (COMP-ICD-001/002, REQ-L1-028).

Registers:

* :class:`Icd` — an Interface Control Document and its current contract

Datenmodell-Konsolidierung Task 28c-2 retired ``IcdVersion`` (and with it its
read-only admin); contract history now lives in ``persistence.ArtifactVersion``
alongside every other artifact type's.

Tenant isolation:
    ``Icd`` inherits ``TenantScopedModel`` (it re-declares ``objects`` and
    ``unscoped`` explicitly in icd.models). ``get_queryset`` uses
    ``unscoped()`` to bypass the tenant filter.
"""
from __future__ import annotations

from django.contrib import admin

from .models import Icd


@admin.register(Icd)
class IcdAdmin(admin.ModelAdmin):
    """Admin view for the Icd header (REQ-L2-ICD-001/002)."""

    list_display = (
        "name",
        "source_element_id",
        "target_element_id",
        "workspace_id",
        "tenant",
        "current_revision",
    )
    list_filter = ("tenant", "workspace_id")
    search_fields = ("name", "source_element_id", "target_element_id")
    ordering = ("-created_at",)
    readonly_fields = ("created_at", "created_by", "modified_at", "modified_by", "version")
    # ``embedding`` (Task 28c-1) is a derived pgvector column, not user data:
    # rendering 384 floats in a form only invites a round-trip that corrupts
    # them on save. Regenerated by the write path / backfill_embeddings.
    exclude = ("embedding",)

    def get_queryset(self, request):
        # CRITICAL: bypass the tenant-isolating default manager.
        return Icd.unscoped.all()
