# Generated by Django 4.2.30 on 2026-07-18 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persistence', '0042_testcase_workflow_status'),
        ('workflow', '0007_backfill_architecture_workflow_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowenginedefinition',
            name='is_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GlobalWorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
                ('item_type', models.CharField(max_length=128)),
                ('preset', models.CharField(max_length=32)),
                ('workflow_json', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant')),
            ],
            options={
                'db_table': 'we_global_definition',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='workflowenginedefinition',
            name='source_global',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_definitions', to='workflow.globalworkflowdefinition'),
        ),
        migrations.AddConstraint(
            model_name='globalworkflowdefinition',
            constraint=models.UniqueConstraint(fields=('tenant', 'item_type', 'preset'), name='uq_we_global_def_tenant_type_preset'),
        ),
    ]
