# Generated by Django 4.2.30 on 2026-06-25 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0004_alter_architectureelement_options_and_more'),
        ('audit', '0002_append_only_trigger'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='auditentry',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='actor',
            field=models.CharField(help_text='User ID or Agent ID string (not a FK to preserve history after user deletion).', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='actor_type',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], help_text="'user' for human actors, 'agent' for MCP clients.", max_length=16),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='api_key_hash',
            field=models.CharField(blank=True, help_text="SHA-256 hash of the API key with 'sha256:' prefix. NULL for REST. NEVER store the raw API key.", max_length=71, null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='change_reason',
            field=models.TextField(blank=True, help_text='Optional human-readable reason for the change (e.g. workflow transition).', null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='client_name',
            field=models.CharField(blank=True, help_text="MCP client identifier (e.g. 'claude-code/1.0'). NULL for REST.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='entity_id',
            field=models.UUIDField(help_text='Primary key of the affected entity.'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='entity_type',
            field=models.CharField(help_text="Type of the affected entity (e.g. 'Requirement', 'TestCase').", max_length=128),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='entity_version',
            field=models.IntegerField(blank=True, help_text='Entity version at the time of the operation (v1: operation-level).', null=True),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='op',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transition', 'Transition')], help_text='Performed operation: create, update, delete, transition.', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='source',
            field=models.CharField(choices=[('rest', 'REST'), ('mcp', 'MCP')], default='rest', help_text="'rest' for REST API callers, 'mcp' for MCP agent callers.", max_length=8),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_set', to='persistence.tenant'),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of the operation; auto-set at INSERT. Partition key.'),
        ),
    ]
