# Generated by Django 4.2.30 on 2026-06-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditentry_managers_alter_auditentry_actor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='op',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transition', 'Transition'), ('baseline.create', 'Baseline Create')], help_text='Performed operation: create, update, delete, transition.', max_length=32),
        ),
    ]
