# Generated by Django 4.2.30 on 2026-07-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_alter_auditentry_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='op',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transition', 'Transition'), ('baseline.create', 'Baseline Create'), ('workspace.close', 'Workspace Close'), ('workspace.reactivate', 'Workspace Reactivate')], help_text='Performed operation: create, update, delete, transition.', max_length=32),
        ),
    ]
