# Generated by Django 6.1.1 on 2026-09-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_alter_auditentry_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditentry',
            name='op',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('transition', 'Transition'), ('baseline.create', 'Baseline Create'), ('workspace.close', 'Workspace Close'), ('workspace.reactivate', 'Workspace Reactivate'), ('workspace.delete', 'Workspace Delete'), ('clone', 'Clone'), ('assign', 'Assign'), ('admin.backup_create', 'Admin Backup Create'), ('admin.restore', 'Admin Restore'), ('permissions.set_rule', 'Permissions Set Rule'), ('permissions.revoke', 'Permissions Revoke'), ('user.create', 'User Create'), ('user.assign_role', 'User Assign Role'), ('user.deactivate', 'User Deactivate'), ('user.activate', 'User Activate'), ('user.suspend_role', 'User Suspend Role'), ('user.reactivate_role', 'User Reactivate Role'), ('user.assign_tenant_admin', 'User Assign Tenant Admin'), ('user.revoke_tenant_admin', 'User Revoke Tenant Admin'), ('ai.decompose', 'AI Decompose'), ('ai.validate', 'AI Validate'), ('ai.check_consistency', 'AI Consistency Check'), ('attribute_migration.apply', 'Attribute Migration Apply'), ('attribute_migration.rollback', 'Attribute Migration Rollback'), ('events.replay', 'Events Replay')], help_text='Performed operation: create, update, delete, transition.', max_length=32),
        ),
    ]
